<a href="https://colab.research.google.com/github/JoseAguirre-10/Algoritmos-DCC-Oto-o2026/blob/main/Tarea_2_Jos%C3%A9_Aguirre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CC3001 Otoño 2026 Tarea 2 [Escriba su nombre aquí]

## Shellsort

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos un arreglo "$d$-ordenado" (donde $d$ es un entero mayor o igual a 1) como un arreglo en que cada elemento está ordenado respecto de sus vecinos que están a $d$ casilleros de distancia. Por ejemplo, en el siguiente diagrama se muestran un arreglo antes y después de ser "3-ordenado", destacando en distintos colores las subsecuencias que se forman al considerar elementos que están a distancia 3:

Antes:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Después:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Noten que el caso particular de un arreglo "1-ordenado" (caso $d=1$) sería lo mismo que un arreglo ordenado.

El algoritmo Shellsort consiste en hacer una secuencia de pasadas $d$-ordenando el arreglo, cada vez con un valor diferente de $d$, siendo la última siempre con $d=1$.

Para hacer una pasada de Shellsort elegimos un valor de $d$ y luego aplicamos una versión modificada de ordenación por inserción. La modificación consiste en que la función ``insertar(a,k)`` compara con el elemento $d$ casilleros más atrás, en lugar de hacerlo con el que está uno más atrás.

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_i,d_{i-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [32]:
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        insertar(a,k)

def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-1]:
        a[j]=a[j-1]
        j-=1
    a[j]=b

Probemos esto para asegurarnos que funcione bien:

In [33]:
import numpy as np

def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print("Arreglo "+str(d)+"-ordenado OK.")

A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar una $d$-ordenación

Modifique el código anterior para que $d$-ordene el arreglo, para un valor de $d$ dado. Para esto, escriba el código de la función ``d_insertar`` en el espacio provisto:

In [127]:
def d_ordena_insercion(a,d):
    n=len(a)
    for k in range(0,n):
        d_insertar(a,k,d)

def d_insertar(a,k,d):
  b = a[k] #aca guardamos la variable que vamos a comparar con los vecinos de la izquierda.
  j = k
  while j-d >=0 and b < a[j-d]: #restamos d porque queremos comparar aquellos que estan d de distancia desde la izquierda
    a[j] = a[j-d] #movemos a la posicion j el de la izquierda y a[k] se mueve d espacios hacia la izquierda
    j-=d
  a[j] = b #aca a[k] ocupa la posicion j .

Pruebe aquí que su algoritmo $3$-ordena correctamente:

In [128]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
d_ordena_insercion(A,3)
print(A)
verifica_d_ordenado(A,3)

[21 35 64 46 56 70 50 82 95 72]
Arreglo 3-ordenado OK.


## 2) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_i=2^i+1$ para $i\ge 1$, y terminando con un $1$. Esto es: $\ldots, 65, 33, 17, 9, 5, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$. Su programa debe partir con el índice $i$ más grande tal que $d_i<n$.

In [158]:
def Shellsort(a):
  """Ordena a usando Shell Sort, con la secuencia de valores …,65,33,17,9,5,3,1"""
  i= len(a)
  while len(a) < (2**i)+1: #mientras el tamaño de la lista sea menor a la ecuación entonces aun no encontramos el i máximo
    i = i-1 #bajamos en uno el exponente del 2
  d = i
  while d >0:
    d_ordena_insercion(a,d)
    d= d-1 #lo hacemos de mayor a menor.

Pruebe aquí su algoritmo de la manera siguiente:

In [157]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
Shellsort(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

In [155]:
A = np.random.randint(0,100, size = 1000)
Shellsort(A)
verifica_d_ordenado(A,1)

Arreglo 1-ordenado OK.


## 3) Probar con una secuencia diferente de valores $d_i$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_i$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

In [154]:
#Usarmos la secuencia de Sedgewick, la cual es más rápida.
def Sedgewicksort(a):
  i = len(a)
  while len(a) < (4**i + 3*(2)**(i-1)+1):
    i -=1
  d = i
  while d > 0:
    d_ordena_insercion(a,d)
    d -=1

In [153]:
A = np.random.randint(0,100, size = 1000)
Sedgewicksort(A)
verifica_d_ordenado(A,1)

Arreglo 1-ordenado OK.


[Referencia de la formula](https://en.wikipedia.org/wiki/Shellsort)

## ¿Qué hay que entregar?

Usted debe entregar este mismo archivo, modificado de acuerdo a lo que se pide. Haga todos los cambios necesarios para explicar y documentar adecuadamente su código. Cite todas las fuentes de información utilizadas. **No olvide poner su nombre en el encabezamiento**.

Recuerde que **esta tarea es individual y que no está permitido hacer uso de inteligencia artificial**. Usted debe estar preparado para explicar su tarea al equipo docente en caso de que se le solicite hacerlo.